deploy:
  provider: launchpad
  slug: ~dfc-d/msmtp-scripts/+git/msmtp-scripts
  oauth_token:
    secure: hCqIv36GQkt0d0MttRA8R8MkhKvQCZdMG2OBZzDfnDgD+aOlSl33+72DDBdhmkpzO79b9NIshtc17q8wa8Iq0SfeF788Jn6dB93YvUbA826aAQNeUsPdZLfcJkZ8Tdirx4algDbWoDL1J8zNDhUDHSeuesU5kdkJneKhKclpmC+eXqW+D/ggLn6ftYetfaDwAU96JBUE9/dbGKBFN4FlYvlh5hu+EkYR1RzosY7pn0x+lVgwxNyv0APtXAIlK6sFfd3cohbNu/espiYkCwmLBxRll4OTohdEu9gphbmPbV9jUiSZfKo6PR+k0YSJ0yTY84oVCRJYzGUjfMBLbVsIpoVU/5+0MCCwivUoQbKES/If1Yx373koa2GZ9jxYBjNMvWyex9mYIwA/sj9b2Wdh4A2+IyFKE2DY9t6ZI/fVKCGFCvxbVovKBuvYFQqg/ULw4dsjRYeiRD1BFGSi/rE+P5ShIAt7Zzpmw5/31g1tAb3Cklyggos+ib7qXZJhVvPvOeb6ZJEO20Og02mfz0pvYzcNHaSfFh6oMRePYddJQyRuopjX9VBSuFBSjuawChTBaZlu6REsg/lcZVZxHrX/iwQzKQPNSm/I4B2Wkr1AVeh+sqHZwCRYW3ZosQbLTCHtNUTnGMG5Gidse7YbfuuR3dDMBNoeQMPDve1yIfy0vrI=
  oauth_token_secret:
    secure: I55+56lJQ4GhauyCipbRDc1UfXJJsHSlvYMSu1LIRR0n66ZoB9huM4UGXgYn3xahAVu7p7fHl15WsGIVpYzvya15VN7lUZo3xA50SHZOKsij0PBpyL3pDFTlvVFrO8R0x8A1YnmAyZVsVMUTePDRM11nSQKr51xwUAPNRWBgIdRSw+q0AE8qJb+bUE8iiV0kHFDBfW5wZy3Q2TUex/m8ZB6GHbVSH++U/eDFPe264Lq1uZIMCNG4BOJ9sMJEIBShZN8hQAvRkMpfSFa7shEJiimx+XSmAQds19fOCOMyhsvHrzlnHFGH3/8He8RhzPk1f2hdToTqXg/icuk0sc4OL067I/iGeJwvLTEcyLSR5weBHsHjaZ3oGHDIeIrlF/haxN+MKD4dLqyM/bkxNG62lj91k2wvfbfllS9rmDyv6H6mU55mVhryk9Cb+OB6QLQbZaCdaHn808afuSzyF63SPIWIhYTmBfBf7dVMZLCvpCZGwIIPp2ErnD5lRvcH7Sl//88xdjWDC8kFagJOk1tC4WdIPXubfBRqFVPfRHOVna1+keR9p/Y06wYKxLKduJJCUDh7qa67nQhoOOSSZTnuheuWZlB4Ao9nawLZhHXvX2nAiIwJBmPXYAUubhCdRPaYiCoBXRNmkGnZANPuggbksev1N2qZIZEFtWw006MBpBA=
language: c
before_install:
  - sudo apt update
  - sudo apt install -y dh-systemd fakeroot
script: "./tests/scripts/prepare_test_environment && ./tests/scripts/run_all_tests"
dist: xenial
branches:
  only:
  - master
  - stable-1.1
  - release-1.2
  - /^\d+\.\d\+\.\d+$/
