#!/bin/sh

if [ -r /etc/msmtpq-mta.conf ]; then
	. /etc/msmtpq-mta.conf
fi

[ -z "$Q" ] && Q=/var/spool/msmtp
[ -z "$LOG" ] && LOG=/var/log/msmtp/queue.log
[ -z "$EMAIL_CONN_TEST" ] && EMAIL_CONN_TEST=n
[ -z "$MSMTP_UMASK" ] && MSMTP_UMASK=077
[ -z "$MSMTP_LOG_UMASK" ] && MSMTP_LOG_UMASK=057
[ -z "$EMAIL_QUEUE_QUIET" ] && EMAIL_QUEUE_QUIET=true
[ "$EMAIL_QUEUE_QUIET" = "false" ] && unset EMAIL_QUEUE_QUIET
[ -z "$MSMTP_IGNORE_NO_RECIPIENTS" ] && MSMTP_IGNORE_NO_RECIPIENTS=true
[ -z "$MSMTP_QUEUE_ONLY" ] && MSMTP_QUEUE_ONLY=false
[ -z "$MSMTP_SEND_DELAY" ] && MSMTP_SEND_DELAY=0

export Q LOG EMAIL_CONN_TEST MSMTP_UMASK MSMTP_LOG_UMASK EMAIL_QUEUE_QUIET MSMTP_IGNORE_NO_RECIPIENTS MSMTP_QUEUE_ONLY MSMTP_SEND_DELAY

exec /usr/bin/msmtpq "$@"

