#!/bin/sh

##--------------------------------------------------------------
##
##  msmtpq-ng-mta:  A wrapper scripts for msmtpq-ng for use as
##                  system MTA
##  Copyright (C) 2016 Daniel Dickinson
##
##  This program is free software: you can redistribute it and/or modify
##  it under the terms of the GNU General Public License as published by
##  the Free Software Foundation, either version 3 of the License, or, at
##  your option, any later version.
##
##--------------------------------------------------------------

## msmtpq-ng-mta
## is only a wrapper
## it invokes the main msmtpq-ng script
##
## all configuration and documentation is in the msmtpq-ng script

## note that for 'special circumstances'
##   (e.g. embedded systems, etc.)
## where the msmtpq-ng script itself is not on the path
## set the environment variable MSMTPQ_NG to the full path
## of msmtpq-ng in /etc/msmtpq-ng-mta.rc
## e.g. 
## MSMTPQ_NG=/path/to/msmtpq-ng

MSMTP_OVERRIDE_CONF=/etc/msmtpq-ng-mta.rc
export MSMTP_OVERRIDE_CONF

if [ "$MSMTP_MTA_SKIP_CONF" != "true" ]; then
	[ -r /etc/msmtpq-ng-mta.rc ] && . /etc/msmtpq-ng-mta.rc
	[ -r ~/.msmtpq-ng-mta.rc ] && . ~/.msmtpq-ng-mta.rc
fi

[ -z "$MSMTP_CONF ] && MSMTP_CONF=/etc/msmtpq-ng-mta-msmtprc
[ -z "$LOG" ] && LOG=syslog
[ -z "$Q" ] && Q=/var/spool/msmtp
[ -z "$MSMTP_LOCK_DIR" ] && MSMTP_LOCK_DIR=/var/lock
[ -z "$MSMTP_LOG_UMASK" ] && MSMTP_LOG_UMASK=057
[ -z "$MSMTP_UMASK" ] && MSMTP_UMASK=007
[ -z "$MSMTP_QUEUE_QUIET" ] && MSMTP_QUEUE_QUIET=true
[ -z "$MSMTP_IGNORE_NO_RECIPIENTS" ] && MSMTP_IGNORE_NO_RECIPIENTS=true
[ -z "$MSMTPQ_NG" ] && MSMTPQ_NG=msmtpq-ng

umask $MSMTP_UMASK

# Create per-user queue dir but only if main queue dir exists
if [ ! -d "${Q}" ] && [ -d "$(dirname "${Q}")" ]; then
	mkdir -p "${Q}"
fi

# Create per-user lock dir
if [ ! -d "${MSMTP_LOCK_DIR}" ]; then
	mkdir -p "${MSMTP_LOCK_DIR}"
fi

export LOG Q MSMTP_LOG_UMASK MSMTP_LOCK_DIR MSMTP_UMASK MSMTP_QUEUE_QUIET MSMTP_IGNORE_NO_RECIPIENTS MSMTPQ_NG MSMTP_CONF

[ -x "$MSMTPQ_NG" ] && exec "$MSMTPQ_NG" "$@"
[ -n "$(which "$MSMTPQ_NG")" ]  && exec msmtpq-ng "$@"

echo "msmtpq-ng-mta: unable to find msmtpq-ng" >&2
# From sysexits.h: EX_OSFILE
exit 72

