#!/bin/sh

if [ ! -x /bin/bash ]; then
	echo "CRITICAL: Bash is required for msmtp-scripts"
	exit 1
fi

mkdir -p ~/log || exit 2
mkdir -p ~/.msmtp.queue || exit 2
mkdir -p ~/.msmtpq.lock || exit 2

cp ./tests/config/msmtpq-ng.rc ~/.msmtpq-ng.rc
