#!/bin/sh

if [ ! -x /bin/sh ]; then
	echo "CRITICAL: /bin/sh is required for msmtp-scripts"
	exit 1
fi

mkdir -p ./tmp/msmtp.queue || exit 2
mkdir -p ./tmp/msmtp.lock || exit 2

cp ./tests/config/msmtpq-ng.rc ./tmp/msmtpq-ng.rc
cp ./tests/config/msmtpq-fail.rc ./tmp/msmtpq-fail.rc
cp ./tests/config/msmtpq-ng-msmtprc ./tmp/msmtpq-ng-msmtprc
